### ISSUE TITLE
Wrong link in the wget command

### ISSUE THREAD

**Issue by chvvkumar** [vikramjakhr/vsphere-vcenter-influx-go#3]
In the readme file, the following line:

wget https://github.com/vikramjakhr/vsphere-vcenter-influx-go/blob/master/vsphere-influxdb.json

should read

wget https://raw.githubusercontent.com/vikramjakhr/vsphere-vcenter-influx-go/master/vsphere-influxdb.json

The current command pulls the html page of the JSON file rather than the JSON file itself.

**Comment by vikramjakhr** [comment]
Updated the URL in the readme. Thanks for pointing out.
